# Generated by Django 4.2.3 on 2023-10-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='cariation_value',
            new_name='variation_value',
        ),
    ]
