# Generated by Django 4.2.1 on 2023-10-24 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product_gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
